In [44]:
# Install the libraries needed for data collection
!pip install yfinance pandas

Requirement already satisfied: yfinance in /usr/local/lib/python3.13/dist-packages (0.2.66)
Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (2.2.3)
Requirement already satisfied: numpy>=1.16.5 in /usr/local/lib/python3.13/dist-packages (from yfinance) (2.1.3)
Requirement already satisfied: requests>=2.31 in /usr/local/lib/python3.13/dist-packages (from yfinance) (2.32.4)
Requirement already satisfied: multitasking>=0.0.7 in /usr/local/lib/python3.13/dist-packages (from yfinance) (0.0.13)
Requirement already satisfied: platformdirs>=2.0.0 in /usr/local/lib/python3.13/dist-packages (from yfinance) (4.13.5)
Requirement already satisfied: pytz>=2022.5 in /usr/local/lib/python3.13/dist-packages (from yfinance) (2025.2)
Requirement already satisfied: frozendict>=2.3.4 in /usr/local/lib/python3.13/dist-packages (from yfinance) (2.4.7)
Requirement already satisfied: peewee>=3.16.2 in /usr/local/lib/python3.13/dist-packages (from yfinance) (4.5.3)
Requirement already satisfied: beautifulsoup4>=4.11.1 in /usr/local/lib/python3.13/dist-packages (from yfinance) (4.13.5)
Requirement already satisfied: curl_cffi>=0.7 in /usr/local/lib/python3.13/dist-packages (from yfinance) (0.16.3)
Requirement already satisfied: protobuf>=3.19.0 in /usr/local/lib/python3.13/dist-packages (from yfinance) (6.33.6)
Requirement already satisfied: websockets>=13.0 in /usr/local/lib/python3.13/dist-packages (from yfinance) (15.0.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas) (2026.5)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.13/dist-packages (from beautifulsoup4>=4.11.1->yfinance) (3.0.3)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.13/dist-packages (from beautifulsoup4>=4.11.1->yfinance) (4.16.0)
Requirement already satisfied: cffi>=2.0.0 in /usr/local/lib/python3.13/dist-packages (from curl_cffi>=0.7->yfinance) (2.1.1)
Requirement already satisfied: certifi>=2024.2.2 in /usr/local/lib/python3.13/dist-packages (from curl_cffi>=0.7->yfinance) (2026.10.19)
Requirement already satisfied: pycparser in /usr/local/lib/python3.13/dist-packages (from cffi>=2.0.0->curl_cffi>=0.7->yfinance) (3.11)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.13/dist-packages (from requests>=2.31->yfinance) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.13/dist-packages (from requests>=2.31->yfinance) (3.20)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.13/dist-packages (from requests>=2.31->yfinance) (2.5.0)

In [45]:
# Import the library used to retrieve financial data
import yfinance as yf

# Select Microsoft using its ticker symbol
msft = yf.Ticker("MSFT")

In [46]:
# Retrieve Microsoft's company information
company_info = msft.info

# Display the company name and industry
print("Company Name:", company_info.get("longName"))
print("Industy:", company_info.get("industry"))
print("Sector:", company_info.get("sector"))

Company Name: Microsoft Corporation
Industy: Software - Infrastructure
Sector: Technology

In [47]:
# Retrieve Microsoft's annual income statement
income_statement = msft.incomestmt

# Display the available financial data
display(income_statement)

                                                      2026-06-30  ...    2023-06-30
Tax Effect Of Unusual Items                         1.110650e+09  ... -2.850000e+06
Tax Rate For Calcs                                  1.940000e-01  ...  1.900000e-01
Normalized EBITDA                                   2.017940e+11  ...  1.051550e+11
Total Unusual Items                                 5.725000e+09  ... -1.500000e+07
Total Unusual Items Excluding Goodwill              5.725000e+09  ... -1.500000e+07
Net Income From Continuing Operation Net Minori...  1.337490e+11  ...  7.236100e+10
Reconciled Depreciation                             3.853400e+10  ...  1.386100e+10
Reconciled Cost Of Revenue                          1.063740e+11  ...  6.586300e+10
EBITDA                                              2.075190e+11  ...  1.051400e+11
EBIT                                                1.689850e+11  ...  9.127900e+10
Net Interest Income                                 2.500000e+08  ...  1.026000e+09
Interest Expense                                    3.051000e+09  ...  1.968000e+09
Interest Income                                     3.301000e+09  ...  2.994000e+09
Normalized Income                                   1.291346e+11  ...  7.237315e+10
Net Income From Continuing And Discontinued Ope...  1.337490e+11  ...  7.236100e+10
Total Expenses                                      1.766020e+11  ...  1.233920e+11
Total Operating Income As Reported                  1.552370e+11  ...  8.852300e+10
Diluted Average Shares                              7.453000e+09  ...  7.472000e+09
Basic Average Shares                                7.429000e+09  ...  7.446000e+09
Diluted EPS                                         1.795000e+01  ...  9.680000e+00
Basic EPS                                           1.800000e+01  ...  9.720000e+00
Diluted NI Availto Com Stockholders                 1.337490e+11  ...  7.236100e+10
Net Income Common Stockholders                      1.337490e+11  ...  7.236100e+10
Net Income                                          1.337490e+11  ...  7.236100e+10
Net Income Including Noncontrolling Interests       1.337490e+11  ...  7.236100e+10
Net Income Continuous Operations                    1.337490e+11  ...  7.236100e+10
Tax Provision                                       3.218500e+10  ...  1.695000e+10
Pretax Income                                       1.659340e+11  ...  8.931100e+10
Other Income Expense                                1.044700e+10  ... -2.380000e+08
Other Non Operating Income Expenses                 4.722000e+09  ... -2.230000e+08
Special Income Charges                             -1.780000e+08  ... -3.000000e+07
Write Off                                           1.780000e+08  ...  3.000000e+07
Gain On Sale Of Security                            5.903000e+09  ...  1.500000e+07
Net Non Operating Interest Income Expense           2.500000e+08  ...  1.026000e+09
Interest Expense Non Operating                      3.051000e+09  ...  1.968000e+09
Interest Income Non Operating                       3.301000e+09  ...  2.994000e+09
Operating Income                                    1.552370e+11  ...  8.852300e+10
Operating Expense                                   7.022800e+10  ...  5.752900e+10
Research And Development                            3.556200e+10  ...  2.719500e+10
Selling General And Administration                  3.466600e+10  ...  3.033400e+10
Selling And Marketing Expense                       2.671000e+10  ...  2.275900e+10
General And Administrative Expense                  7.956000e+09  ...  7.575000e+09
Other Gand A                                        7.956000e+09  ...  7.575000e+09
Gross Profit                                        2.254650e+11  ...  1.460520e+11
Cost Of Revenue                                     1.063740e+11  ...  6.586300e+10
Total Revenue                                       3.318390e+11  ...  2.119150e+11
Operating Revenue                                   3.318390e+11  ...  2.119150e+11

[47 rows x 4 columns]

In [48]:
# Retrieve Microsoft's annual balance sheet
balance_sheet = msft.balance_sheet

# Display the available financial data
display(balance_sheet)

                                                    2026-06-30  ...  2022-06-30
Ordinary Shares Number                            7.428435e+09  ...         NaN
Share Issued                                      7.428435e+09  ...         NaN
Net Debt                                          1.935900e+10  ...         NaN
Total Debt                                        5.682600e+10  ...         NaN
Tangible Book Value                               3.041270e+11  ...         NaN
...                                                        ...  ...         ...
Cash Cash Equivalents And Short Term Investments  7.665100e+10  ...         NaN
Other Short Term Investments                      5.571600e+10  ...         NaN
Cash And Cash Equivalents                         2.093500e+10  ...         NaN
Cash Equivalents                                  7.876000e+09  ...         NaN
Cash Financial                                    1.305900e+10  ...         NaN

[79 rows x 5 columns]

In [49]:
# Retrieve Microsoft's annual cash flow statement
cash_flow =msft.cashflow

# Display the available financial data
display(cash_flow)

                                                  2026-06-30  ...   2022-06-30
Free Cash Flow                                  6.698700e+10  ...          NaN
Repurchase Of Capital Stock                    -2.227100e+10  ...          NaN
Repayment Of Debt                              -3.000000e+09  ...          NaN
Issuance Of Debt                                0.000000e+00  ...          NaN
Issuance Of Capital Stock                       2.009000e+09  ...          NaN
Capital Expenditure                            -1.159480e+11  ...          NaN
End Cash Position                               2.093500e+10  ...          NaN
Beginning Cash Position                         3.024200e+10  ...          NaN
Effect Of Exchange Rate Changes                -1.960000e+08  ...          NaN
Changes In Cash                                -9.111000e+09  ...          NaN
Financing Cash Flow                            -5.254600e+10  ...          NaN
Cash Flow From Continuing Financing Activities -5.254600e+10  ...          NaN
Net Other Financing Charges                    -2.839000e+09  ...          NaN
Cash Dividends Paid                            -2.644500e+10  ...          NaN
Common Stock Dividend Paid                     -2.644500e+10  ...          NaN
Net Common Stock Issuance                      -2.026200e+10  ...          NaN
Common Stock Payments                          -2.227100e+10  ...          NaN
Common Stock Issuance                           2.009000e+09  ...          NaN
Net Issuance Payments Of Debt                  -3.000000e+09  ...          NaN
Net Short Term Debt Issuance                    0.000000e+00  ...          NaN
Short Term Debt Issuance                                 NaN  ...          0.0
Net Long Term Debt Issuance                    -3.000000e+09  ...          NaN
Long Term Debt Payments                        -3.000000e+09  ...          NaN
Long Term Debt Issuance                         0.000000e+00  ...          NaN
Investing Cash Flow                            -1.395000e+11  ...          NaN
Cash Flow From Continuing Investing Activities -1.395000e+11  ...          NaN
Net Other Investing Changes                    -1.986100e+10  ...          NaN
Net Investment Purchase And Sale               -1.948000e+09  ...          NaN
Sale Of Investment                              5.640300e+10  ...          NaN
Purchase Of Investment                         -5.835100e+10  ...          NaN
Net Business Purchase And Sale                 -1.743000e+09  ...          NaN
Purchase Of Business                           -1.743000e+09  ...          NaN
Net PPE Purchase And Sale                      -1.159480e+11  ...          NaN
Purchase Of PPE                                -1.159480e+11  ...          NaN
Operating Cash Flow                             1.829350e+11  ...          NaN
Cash Flow From Continuing Operating Activities  1.829350e+11  ...          NaN
Change In Working Capital                      -4.895000e+09  ...          NaN
Change In Other Working Capital                 7.486000e+09  ...          NaN
Change In Other Current Liabilities             2.140000e+09  ...          NaN
Change In Other Current Assets                 -6.591000e+09  ...          NaN
Change In Payables And Accrued Expense          5.268000e+09  ...          NaN
Change In Payable                               5.268000e+09  ...          NaN
Change In Account Payable                       5.268000e+09  ...          NaN
Change In Tax Payable                                    NaN  ...  696000000.0
Change In Income Tax Payable                             NaN  ...  696000000.0
Change In Inventory                            -4.610000e+08  ...          NaN
Change In Receivables                          -1.273700e+10  ...          NaN
Changes In Account Receivables                 -1.273700e+10  ...          NaN
Stock Based Compensation                        1.240500e+10  ...          NaN
Unrealized Gain Loss On Investment Securities            NaN  ... -509000000.0
Asset Impairment Charge                                  NaN  ...  101000000.0
Deferred Tax                                    1.418900e+10  ...          NaN
Deferred Income Tax                             1.418900e+10  ...          NaN
Depreciation Amortization Depletion             3.853400e+10  ...          NaN
Depreciation And Amortization                   3.853400e+10  ...          NaN
Depreciation                                    3.853400e+10  ...          NaN
Operating Gains Losses                         -1.104700e+10  ...          NaN
Gain Loss On Investment Securities                       NaN  ...   -1000000.0
Net Income From Continuing Operations           1.337490e+11  ...          NaN

[59 rows x 5 columns]

In [50]:
# Retrieve Microsoft's historical stock prices for the last five years
historical_prices = msft.history(period="5y")

# Display the first five rows
display(historical_prices.head())

                                 Open        High  ...  Dividends  Stock Splits
Date                                               ...
2021-10-25 00:00:00-04:00  296.901210  296.939607  ...        0.0           0.0
2021-10-26 00:00:00-04:00  298.475174  299.818786  ...        0.0           0.0
2021-10-27 00:00:00-04:00  303.273803  312.967054  ...        0.0           0.0
2021-10-28 00:00:00-04:00  311.268293  311.786554  ...        0.0           0.0
2021-10-29 00:00:00-04:00  311.076392  318.629441  ...        0.0           0.0

[5 rows x 7 columns]

In [51]:
# Retrieve selected financial metrics from the company information
financial_metrices = {
    "EPS": company_info.get("trailingEps"),
    "P/E Ratio": company_info.get("trailingPD"),
    "Market Capitalization": company_info.get("marketcap")
}

# Dispaly the selected financial metrices
print(financial_metrices)

{'EPS': 17.95, 'P/E Ratio': None, 'Market Capitalization': None}

In [52]:
# Check the type and size of each collected dataset
print("Company information:", type(company_info))
print("Income statement:", income_statement.shape)
print("Balance sheet:", type(balance_sheet.shape))
print("Cash flow statement:", type(cash_flow.shape))
print("Historical  stock prices:", type(historical_prices.shape))
print("Financial Metrices:", type(financial_metrices))

Company information: <class 'dict'>
Income statement: (47, 4)
Balance sheet: <class 'tuple'>
Cash flow statement: <class 'tuple'>
Historical  stock prices: <class 'tuple'>
Financial Metrices: <class 'dict'>

In [53]:
print("Balance sheet:", type(balance_sheet), balance_sheet)
print("Cash flow:", type(cash_flow), cash_flow)
print("Historical prices:", type(historical_prices), historical_prices)

Balance sheet: <class 'pandas.core.frame.DataFrame'>                                                     2026-06-30  ...  2022-06-30
Ordinary Shares Number                            7.428435e+09  ...         NaN
Share Issued                                      7.428435e+09  ...         NaN
Net Debt                                          1.935900e+10  ...         NaN
Total Debt                                        5.682600e+10  ...         NaN
Tangible Book Value                               3.041270e+11  ...         NaN
...                                                        ...  ...         ...
Cash Cash Equivalents And Short Term Investments  7.665100e+10  ...         NaN
Other Short Term Investments                      5.571600e+10  ...         NaN
Cash And Cash Equivalents                         2.093500e+10  ...         NaN
Cash Equivalents                                  7.876000e+09  ...         NaN
Cash Financial                                    1.305900e+10  ...         NaN

[79 rows x 5 columns]
Cash flow: <class 'pandas.core.frame.DataFrame'>                                                   2026-06-30  ...   2022-06-30
Free Cash Flow                                  6.698700e+10  ...          NaN
Repurchase Of Capital Stock                    -2.227100e+10  ...          NaN
Repayment Of Debt                              -3.000000e+09  ...          NaN
Issuance Of Debt                                0.000000e+00  ...          NaN
Issuance Of Capital Stock                       2.009000e+09  ...          NaN
Capital Expenditure                            -1.159480e+11  ...          NaN
End Cash Position                               2.093500e+10  ...          NaN
Beginning Cash Position                         3.024200e+10  ...          NaN
Effect Of Exchange Rate Changes                -1.960000e+08  ...          NaN
Changes In Cash                                -9.111000e+09  ...          NaN
Financing Cash Flow                            -5.254600e+10  ...          NaN
Cash Flow From Continuing Financing Activities -5.254600e+10  ...          NaN
Net Other Financing Charges                    -2.839000e+09  ...          NaN
Cash Dividends Paid                            -2.644500e+10  ...          NaN
Common Stock Dividend Paid                     -2.644500e+10  ...          NaN
Net Common Stock Issuance                      -2.026200e+10  ...          NaN
Common Stock Payments                          -2.227100e+10  ...          NaN
Common Stock Issuance                           2.009000e+09  ...          NaN
Net Issuance Payments Of Debt                  -3.000000e+09  ...          NaN
Net Short Term Debt Issuance                    0.000000e+00  ...          NaN
Short Term Debt Issuance                                 NaN  ...          0.0
Net Long Term Debt Issuance                    -3.000000e+09  ...          NaN
Long Term Debt Payments                        -3.000000e+09  ...          NaN
Long Term Debt Issuance                         0.000000e+00  ...          NaN
Investing Cash Flow                            -1.395000e+11  ...          NaN
Cash Flow From Continuing Investing Activities -1.395000e+11  ...          NaN
Net Other Investing Changes                    -1.986100e+10  ...          NaN
Net Investment Purchase And Sale               -1.948000e+09  ...          NaN
Sale Of Investment                              5.640300e+10  ...          NaN
Purchase Of Investment                         -5.835100e+10  ...          NaN
Net Business Purchase And Sale                 -1.743000e+09  ...          NaN
Purchase Of Business                           -1.743000e+09  ...          NaN
Net PPE Purchase And Sale                      -1.159480e+11  ...          NaN
Purchase Of PPE                                -1.159480e+11  ...          NaN
Operating Cash Flow                             1.829350e+11  ...          NaN
Cash Flow From Continuing Operating Activities  1.829350e+11  ...          NaN
Change In Working Capital                      -4.895000e+09  ...          NaN
Change In Other Working Capital                 7.486000e+09  ...          NaN
Change In Other Current Liabilities             2.140000e+09  ...          NaN
Change In Other Current Assets                 -6.591000e+09  ...          NaN
Change In Payables And Accrued Expense          5.268000e+09  ...          NaN
Change In Payable                               5.268000e+09  ...          NaN
Change In Account Payable                       5.268000e+09  ...          NaN
Change In Tax Payable                                    NaN  ...  696000000.0
Change In Income Tax Payable                             NaN  ...  696000000.0
Change In Inventory                            -4.610000e+08  ...          NaN
Change In Receivables                          -1.273700e+10  ...          NaN
Changes In Account Receivables                 -1.273700e+10  ...          NaN
Stock Based Compensation                        1.240500e+10  ...          NaN
Unrealized Gain Loss On Investment Securities            NaN  ... -509000000.0
Asset Impairment Charge                                  NaN  ...  101000000.0
Deferred Tax                                    1.418900e+10  ...          NaN
Deferred Income Tax                             1.418900e+10  ...          NaN
Depreciation Amortization Depletion             3.853400e+10  ...          NaN
Depreciation And Amortization                   3.853400e+10  ...          NaN
Depreciation                                    3.853400e+10  ...          NaN
Operating Gains Losses                         -1.104700e+10  ...          NaN
Gain Loss On Investment Securities                       NaN  ...   -1000000.0
Net Income From Continuing Operations           1.337490e+11  ...          NaN

[59 rows x 5 columns]
Historical prices: <class 'pandas.core.frame.DataFrame'>                                  Open        High  ...  Dividends  Stock Splits
Date                                               ...
2021-10-25 00:00:00-04:00  296.901210  296.939607  ...        0.0           0.0
2021-10-26 00:00:00-04:00  298.475174  299.818786  ...        0.0           0.0
2021-10-27 00:00:00-04:00  303.273803  312.967054  ...        0.0           0.0
2021-10-28 00:00:00-04:00  311.268293  311.786554  ...        0.0           0.0
2021-10-29 00:00:00-04:00  311.076392  318.629441  ...        0.0           0.0
...                               ...         ...  ...        ...           ...
2026-10-19 00:00:00-04:00  528.700012  535.570007  ...        0.0           0.0
2026-10-20 00:00:00-04:00  533.909973  534.210022  ...        0.0           0.0
2026-10-21 00:00:00-04:00  529.440002  533.280029  ...        0.0           0.0
2026-10-22 00:00:00-04:00  533.140015  533.599976  ...        0.0           0.0
2026-10-23 00:00:00-04:00  517.750000  525.770020  ...        0.0           0.0

[1255 rows x 7 columns]

In [54]:
# Convert company information into readable text
company_text = "\n".join(
    f"{key}: {value}"
    for key, value in company_info.items()
)

# convert the income statement into readable text
income_text = income_statement.to_string()

# convert the balance sheet into readable text
balance_text = balance_sheet.to_string()

# convert the cash flow statement into readable text
cash_flow_text = cash_flow.to_string()

# convert financial metrices into readable text
metrices_text = "\n".join(
     f"{key}: {value}"
     for key, value in financial_metrices.items()
 )

print("Company information text prepared:", len(company_text), "characters")
print("Income statement text prepared:", len(income_text), "characters")
print("Balance sheet text prepared:", len(balance_text), "characters")
print("Cash flow text prepared:", len(cash_flow_text), "characters")
print("Financial metrices text prepared:", len(metrices_text), "characters")

Company information text prepared: 8944 characters
Income statement text prepared: 5519 characters
Balance sheet text prepared: 11119 characters
Cash flow text prepared: 6959 characters
Financial metrices text prepared: 54 characters

In [55]:
# Combine the collected financial information into one document
financial_document = f"""
MICROSOFT COMPANY INFORMATION
{company_text}

MICROSOFT INCOME STATEMENT
{income_text}

MICROSOFT BALANCE SHEET
{balance_text}

MICROSOFT CASH FLOW STATEMENT
{cash_flow_text}

MICROSOFT FINANCIAL METRICES
{metrices_text}
"""
print("Financial document created successfully.")
print("Total characters:", len(financial_document))
print("\nPreview of the document:")
print(financial_document[:500])

Financial document created successfully.
Total characters: 32745

Preview of the document:

MICROSOFT COMPANY INFORMATION
address1: One Microsoft Way
city: Redmond
state: WA
zip: 98052-6399
country: United States
phone: 425 882 8080
website: https://www.microsoft.com
industry: Software - Infrastructure
industryKey: software-infrastructure
industryDisp: Software - Infrastructure
sector: Technology
sectorKey: technology
sectorDisp: Technology
longBusinessSummary: Microsoft Corporation, a technology company, develops and supports a portfolio of technology solutions for individuals and bu

In [56]:
# Split the financial document into chunks of 1000 characters
# Keep 200 characters overlapping between consecutive chunks

chunk_size = 1000
overlap = 200

text_chunks = []

for start in range(0, len(financial_document), chunk_size - overlap):
    text_chunks.append(financial_document[start:start + chunk_size])

print("Document length:", len(financial_document))
print("Total text chunks:", len(text_chunks))
print("First chunk length:", len(text_chunks[0]))
print("Last chunk length:", len(text_chunks[-1]))

Document length: 32745
Total text chunks: 41
First chunk length: 1000
Last chunk length: 745

In [57]:
print("Document length:", len(financial_document))
print("Chunk count:", len(text_chunks))
print("Chunk lengths:", [len(chunk) for chunk in text_chunks[:5]])

Document length: 32745
Chunk count: 41
Chunk lengths: [1000, 1000, 1000, 1000, 1000]

In [58]:
print("Document length:", len(financial_document))
print("Chunk count:", len(text_chunks))
print("Last chunk length:", len(text_chunks[-1]))

Document length: 32745
Chunk count: 41
Last chunk length: 745

In [59]:

import importlib.util

print(
    "Sentence Transformers installed:",
    importlib.util.find_spec("sentence_transformers") is not None
)

Sentence Transformers installed: True

In [60]:
from sentence_transformers import SentenceTransformer

embedding_model = SentenceTransformer("all-MiniLM-L6-v2")

print("Embedding Model Loaded Successfully!")

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

Embedding Model Loaded Successfully!

In [61]:
# Convert each text chunk into a numerical embedding
embeddings = embedding_model.encode(text_chunks)

print("Number of embeddings:", len(embeddings))
print("Embedding dimensions:", embeddings.shape)

Number of embeddings: 41
Embedding dimensions: (41, 384)

In [62]:
!pip install -q faiss-cpu

In [63]:
import faiss
import numpy as np

# convert embeddings to the format FAISS requires
embeddings = np.array(embeddings, dtype="float32")

# create the FAISS index
index = faiss.IndexFlatL2(embeddings.shape[1])

# add all embeddings to the index
index.add(embeddings)

print("FAISS index created successfully!")
print("Total vectors indexed:", index.ntotal)

FAISS index created successfully!
Total vectors indexed: 41

In [64]:
# Search for text chunks related to Microsoft's revenue
query = "Microsoft total revenue for fiscal year 2026"

# Convert the question into an embedding
query_embedding = embedding_model.encode([query])
query_embedding = np.array(query_embedding, dtype="float32")

# Retrieve the 3 closest chunks
distances, indices = index.search(query_embedding, k=3)

print("Search query:", query)
print("\nRelevent text chunks:\n")

for i in indices[0]:
  print(text_chunks[i][:300])
  print("-" * 50)

Search query: Microsoft total revenue for fiscal year 2026

Relevent text chunks:

entType': 'DIVIDEND', 'dateEpochMs': 1795060800000, 'amount': '0.98'}}]
preMarketTime: 1793014950
regularMarketTime: 1792785601
displayName: Microsoft
trailingPegRatio: 1.7034

MICROSOFT INCOME STATEMENT
                                                              2026-06-30    2025-06-30    2024-0
--------------------------------------------------

MICROSOFT COMPANY INFORMATION
address1: One Microsoft Way
city: Redmond
state: WA
zip: 98052-6399
country: United States
phone: 425 882 8080
website: https://www.microsoft.com
industry: Software - Infrastructure
industryKey: software-infrastructure
industryDisp: Software - Infrastructure
sector: Te
--------------------------------------------------
and other cloud services; SQL Server, Windows Server, Visual Studio, System Center, and related client access licenses; and enterprise support services, industry solutions, Microsoft partner network, and learning experience. The company's More Personal Computing segment provides Windows OEM licensin
--------------------------------------------------

In [65]:
import importlib.util

print("Google GenAI library installed:",
      importlib.util.find_spec("google.genai") is not None)

Google GenAI library installed: True

In [66]:
from google import genai
from google.colab import userdata

api_key = userdata.get("GOOGLE_API_KEY")
client = genai.Client(api_key=api_key)

print("Gemimi client created successfully!")

Gemimi client created successfully!

In [67]:
response = client.models.generate_content(
    model="gemini-3.5-flash",
    contents="In one sentence, What is fundamental stock analysis?"
)

print(response.text)

Fundamental stock analysis is a method of evaluating a company's financial health, industry position, and broader economic conditions to determine its true intrinsic value and decide whether its stock is currently under- or overvalued.

In [81]:
def retrieve_context(question, k=8):
  # convert the question into an embedding
  query_embedding = embedding_model.encode([question])
  query_embedding = np.array(query_embedding, dtype="float32")

  # Find the 8 most relevent text chunks
  distances, indices = index.search(query_embedding, k)

  # Combine the retrieved chunks into one context
  context = "\n\n".join(
      text_chunks[i]
      for i in indices[0]
      if i != -1
  )

  return context

print("Retrievel function created successfully!")

Retrievel function created successfully!

In [82]:
def ask_financial_question(question):
  # Retrieve relevent information from the financial document
  context = retrieve_context(question, k=8)

  # Ask Gemini to answer using the retrieved information
  prompt = f"""
  Answer the question only using the financial context below.
  If the answer is not available in the context, say so.

  Financial context:
  {context}

  Question: {question}
  """

  response = client.models.generate_content(
      model="gemini-3.5-flash",
      contents=prompt
  )

  return response.text

print("Financial question-answering function created successfully!")

Financial question-answering function created successfully!

In [83]:
question = "What was Microsoft's total revenue in fiscal year 2026?"

answer = ask_financial_question(question)

print("Question:", question)
print("\nAnswer:", answer)

Question: What was Microsoft's total revenue in fiscal year 2026?

Answer: Based on the provided financial context, Microsoft's total revenue for fiscal year 2026 (ending 2026-06-30) was **3.318390e+11** (or **$331,839,012,864**).

In [84]:
print(income_statement)

                                                      2026-06-30  ...    2023-06-30
Tax Effect Of Unusual Items                         1.110650e+09  ... -2.850000e+06
Tax Rate For Calcs                                  1.940000e-01  ...  1.900000e-01
Normalized EBITDA                                   2.017940e+11  ...  1.051550e+11
Total Unusual Items                                 5.725000e+09  ... -1.500000e+07
Total Unusual Items Excluding Goodwill              5.725000e+09  ... -1.500000e+07
Net Income From Continuing Operation Net Minori...  1.337490e+11  ...  7.236100e+10
Reconciled Depreciation                             3.853400e+10  ...  1.386100e+10
Reconciled Cost Of Revenue                          1.063740e+11  ...  6.586300e+10
EBITDA                                              2.075190e+11  ...  1.051400e+11
EBIT                                                1.689850e+11  ...  9.127900e+10
Net Interest Income                                 2.500000e+08  ...  1.026000e+09
Interest Expense                                    3.051000e+09  ...  1.968000e+09
Interest Income                                     3.301000e+09  ...  2.994000e+09
Normalized Income                                   1.291346e+11  ...  7.237315e+10
Net Income From Continuing And Discontinued Ope...  1.337490e+11  ...  7.236100e+10
Total Expenses                                      1.766020e+11  ...  1.233920e+11
Total Operating Income As Reported                  1.552370e+11  ...  8.852300e+10
Diluted Average Shares                              7.453000e+09  ...  7.472000e+09
Basic Average Shares                                7.429000e+09  ...  7.446000e+09
Diluted EPS                                         1.795000e+01  ...  9.680000e+00
Basic EPS                                           1.800000e+01  ...  9.720000e+00
Diluted NI Availto Com Stockholders                 1.337490e+11  ...  7.236100e+10
Net Income Common Stockholders                      1.337490e+11  ...  7.236100e+10
Net Income                                          1.337490e+11  ...  7.236100e+10
Net Income Including Noncontrolling Interests       1.337490e+11  ...  7.236100e+10
Net Income Continuous Operations                    1.337490e+11  ...  7.236100e+10
Tax Provision                                       3.218500e+10  ...  1.695000e+10
Pretax Income                                       1.659340e+11  ...  8.931100e+10
Other Income Expense                                1.044700e+10  ... -2.380000e+08
Other Non Operating Income Expenses                 4.722000e+09  ... -2.230000e+08
Special Income Charges                             -1.780000e+08  ... -3.000000e+07
Write Off                                           1.780000e+08  ...  3.000000e+07
Gain On Sale Of Security                            5.903000e+09  ...  1.500000e+07
Net Non Operating Interest Income Expense           2.500000e+08  ...  1.026000e+09
Interest Expense Non Operating                      3.051000e+09  ...  1.968000e+09
Interest Income Non Operating                       3.301000e+09  ...  2.994000e+09
Operating Income                                    1.552370e+11  ...  8.852300e+10
Operating Expense                                   7.022800e+10  ...  5.752900e+10
Research And Development                            3.556200e+10  ...  2.719500e+10
Selling General And Administration                  3.466600e+10  ...  3.033400e+10
Selling And Marketing Expense                       2.671000e+10  ...  2.275900e+10
General And Administrative Expense                  7.956000e+09  ...  7.575000e+09
Other Gand A                                        7.956000e+09  ...  7.575000e+09
Gross Profit                                        2.254650e+11  ...  1.460520e+11
Cost Of Revenue                                     1.063740e+11  ...  6.586300e+10
Total Revenue                                       3.318390e+11  ...  2.119150e+11
Operating Revenue                                   3.318390e+11  ...  2.119150e+11

[47 rows x 4 columns]

In [85]:
question = "What was Microsoft's net income for fiscal year 2026?"
answer = ask_financial_question(question)

print("Question:", question)
print("\nAnswer:", answer)

Question: What was Microsoft's net income for fiscal year 2026?

Answer: Based on the provided financial context, Microsoft's **Net Income From Continuing Operation Net Minority Interest** for fiscal year 2026 (ending 2026-06-30) was **1.337490e+11** (or **$133,749,000,000**).

In [86]:
question = "What was Microsoft's P/E ratio for fiscal year 2026?"
answer = ask_financial_question(question)

print("Question:", question)
print("\nAnswer:", answer)

Question: What was Microsoft's P/E ratio for fiscal year 2026?

Answer: Based on the provided context, Microsoft's P/E ratio is listed as **None** (not available).


## Testing and Results

The RAG-based financial analysis system was tested using three questions about Microsoft (MSFT).

1. **Total Revenue (FY 2026):** Approximately $331.839 billion. The result matched the original income statement.
2. **Net Income (FY 2026):** Approximately $133.749 billion. The result matched the original income statement.
3. **P/E Ratio:** Returned `None` (not available), consistent with the financial metrics retrieved.

### Conclusion
The system successfully answered these three test questions using the retrieved financial context. The tests also checked how the system handles unavailable information.

### Limitation
The system's accuracy depends on the source data, text chunking, retrieval quality, and the language model's response. More tests are needed before concluding that all answers are reliable.